// All products data - matches schema.ts structure
export const allProducts = [
	{
		id: 1,
		name: "LaunchPad AI",
		slug: "launchpad-ai",
		tagline: "Build AI products faster",
		description:
			"Create and deploy AI-powered applications with modern workflows.",
		websiteUrl: "https://launchpadai.dev",
		tags: ["Next.js", "Tailwind CSS", "Full Stack"],
		createdAt: new Date(Date.now() - 1 * 24 * 60 * 60 * 1000),
		approvedAt: new Date(Date.now() - 1 * 24 * 60 * 60 * 1000),
		status: "approved" as const,
		submittedBy: "john@example.com",
		voteCount: 70,
	},
	{
		id: 2,
		name: "FocusBoard",
		slug: "focusboard",
		tagline: "Plan and organize your work",
		description: "Collaborate with teams and manage projects efficiently.",
		websiteUrl: "https://focusboard.app",
		tags: ["Productivity", "SaaS"],
		createdAt: new Date("2024-01-18"),
		approvedAt: new Date("2024-01-19"),
		status: "approved" as const,
		submittedBy: "mike@example.com",
		voteCount: 207,
	},
	{
		id: 3,
		name: "PixelForge",
		slug: "pixelforge",
		tagline: "Design beautiful interfaces",
		description: "Create modern UI designs with reusable components.",
		websiteUrl: "https://pixelforge.design",
		tags: ["Developer Tools", "Design"],
		createdAt: new Date(Date.now() - 2 * 24 * 60 * 60 * 1000),
		approvedAt: new Date(Date.now() - 2 * 24 * 60 * 60 * 1000),
		status: "approved" as const,
		submittedBy: "alex@example.com",
		voteCount: 156,
	},
	{
		id: 4,
		name: "CloudTrack",
		slug: "cloudtrack",
		tagline: "Monitor your cloud resources",
		description: "Track infrastructure performance and optimize usage.",
		websiteUrl: "https://cloudtrack.io",
		tags: ["Marketing", "SaaS", "Conversion"],
		createdAt: new Date("2024-01-20"),
		approvedAt: new Date("2024-01-21"),
		status: "approved" as const,
		submittedBy: "proofy@example.com",
		voteCount: 523,
	},
	{
		id: 5,
		name: "WriteFlow",
		slug: "writeflow",
		tagline: "AI writing assistant for creators",
		description: "Generate content and organize ideas effortlessly.",
		websiteUrl: "https://writeflow.ai",
		tags: ["SaaS", "Pricing", "Global"],
		createdAt: new Date(Date.now() - 4 * 24 * 60 * 60 * 1000),
		approvedAt: new Date(Date.now() - 4 * 24 * 60 * 60 * 1000),
		status: "approved" as const,
		submittedBy: "parity@example.com",
		voteCount: 87,
	},
	{
		id: 6,
		name: "SecureVault",
		slug: "securevault",
		tagline: "Keep secrets safe",
		description: "Securely manage credentials and sensitive information.",
		websiteUrl: "https://securevault.dev",
		tags: ["Analytics", "Design", "SaaS"],
		createdAt: new Date("2024-01-28"),
		approvedAt: new Date("2024-01-29"),
		status: "approved" as const,
		submittedBy: "data@example.com",
		voteCount: 634,
	},
	{
		id: 7,
		name: "GrowthLoop",
		slug: "growthloop",
		tagline: "Automate customer engagement",
		description: "Run smarter marketing campaigns with automation.",
		websiteUrl: "https://growthloop.app",
		tags: ["Marketing", "Email", "SaaS"],
		createdAt: new Date(Date.now() - 1 * 24 * 60 * 60 * 1000),
		approvedAt: new Date(Date.now() - 1 * 24 * 60 * 60 * 1000),
		status: "approved" as const,
		submittedBy: "email@example.com",
		voteCount: 20,
	},
	{
		id: 8,
		name: "DevMetrics",
		slug: "devmetrics",
		tagline: "Engineering insights in one dashboard",
		description: "Measure delivery performance and team productivity.",
		websiteUrl: "https://devmetrics.io",
		tags: ["Developer Tools", "API", "Infrastructure"],
		createdAt: new Date(Date.now() - 5 * 24 * 60 * 60 * 1000),
		approvedAt: new Date(Date.now() - 5 * 24 * 60 * 60 * 1000),
		status: "approved" as const,
		submittedBy: "api@example.com",
		voteCount: 205,
	},
	{
		id: 9,
		name: "CareerBoost",
		slug: "careerboost",
		tagline: "Grow your developer career",
		description: "Learn leadership, mentoring, and career advancement.",
		websiteUrl: "https://careerboost.dev",
		tags: ["Leadership", "Management", "Development"],
		createdAt: new Date(Date.now() - 3 * 24 * 60 * 60 * 1000),
		approvedAt: new Date(Date.now() - 3 * 24 * 60 * 60 * 1000),
		status: "pending" as const,
		submittedBy: "kulkarni.ankita09@gmail.com",
		voteCount: 340,
	},
];
